### ISSUE TITLE
Dependency error installing this plugin

### ISSUE THREAD

**Issue by diegobas** [nettantra/filament-slider-input-field#1]
- Laravel Version: 9.42.2  
- PHP Version: 8.0.6  
- Composer Version: 2.3.10  
- Filament Version: v2.16.53  

I get an error trying to install this plugin:

`composer require nettantra/filament-slider-input-field`

Error:

**Your requirements could not be resolved to an installable set of packages.**

  Problem 1
    - Root composer.json requires nettantra/filament-slider-input-field ^0.0.2 -> satisfiable by nettantra/filament-slider-input-field[v0.0.2].
    - nettantra/filament-slider-input-field v0.0.2 requires jantinnerezo/livewire-range-slider dev-fix-issue-12 -> found jantinnerezo/livewire-range-slider[dev-feat/vite-migration, dev-main, 1.0.0, 1.0.1, v1.0.1.x-dev] but it does not match the constraint.  

You can also try re-running composer require with an explicit version constraint, e.g. "composer require nettantra/filament-slider-input-field:*" to figure out if any version is installable, or "composer require nettantra/filament-slider-input-field:^2.1" if you know which you need.

**Installation failed, reverting ./composer.json and ./composer.lock to their original content.**

**Comment by devadattas** [comment]
@diegobas For some strange reason the VCS Custom repository approach is not working as per https://getcomposer.org/doc/05-repositories.md#vcs

**Comment by devadattas** [comment]
I have raised a ticket in the composer repository https://github.com/composer/composer/issues/11211

**Comment by studiowizjo** [comment]
Unfortunately error still persist:

```php
  Problem 1
    - nettantra/filament-slider-input-field[v0.0.1, ..., v0.0.2] require jantinnerezo/livewire-range-slider dev-fix-issue-12 -> found jantinnerezo/livewire-range-slider[dev-feat/vite-migration, dev-main, 1.0.0, 1.0.1, v1.0.1.x-dev] but it does not match the constraint.
    - nettantra/filament-slider-input-field[v0.0.3, ..., v0.0.4] require jantinnerezo/livewire-range-slider dev-main -> found jantinnerezo/livewire-range-slider[dev-main] but it does not match your minimum-stability.
    - Root composer.json requires nettantra/filament-slider-input-field * -> satisfiable by nettantra/filament-slider-input-field[v0.0.1, v0.0.2, v0.0.3, v0.0.4].
```

I have tried to install it also with "-W" flag to update all dependencies or installing any version, but without success.
